export interface VariableNode {
  id: string;
  label: string;
  type: 'input' | 'output' | 'social';
  description: string;
  influenceScore: number;
  historicalTrend: number[];
  connectedIds: string[];
  x: number;
  y: number;
}

export interface SimulationInputs {
  priceChange: number;      // -20 to +40%
  deliverySpeed: number;    // 1 (Same day), 2 (2-day), 5 (5-day standard)
  discountRate: number;     // 0 to 50%
  marketingSpend: number;   // -20 to +50%
  procurementVol: number;   // -20 to +50%
  crisis: string;           // 'none', 'flood', 'fuel_spike', 'seller_strike', 'festival'
}

export interface SimulationResult {
  revenueChange: number;
  customerTrust: number;
  sellerHealth: number;
  carbonEmissionChange: number;
  workerStress: number;
  marketplaceHealth: number;
  ethicalRisk: 'Low' | 'Medium' | 'High';
  inventoryWasteUnits: number;
  inventoryWasteCost: number;
  trustProjected90Days: number;
  
  // Detail breakdowns
  avgSellerProfit: number;
  smallSellerSurvival: number;
  sellerChurnProb: number;
  fairnessIndex: number;
  greenDeliveryPct: number;
  sustainableShippingScore: number;
  warehouseLoad: number;
  driverWorkload: number;
  deliveryUtil: number;
  pricingRiskReason: string;
  wasteRecommendation: string;
  
  // Weekly predictions
  timeline: {
    week: number;
    title: string;
    description: string;
    impact: 'good' | 'neutral' | 'bad';
    metric: string;
  }[];
  
  // AI Recommendation Alternative
  aiSuggestion: {
    priceChange: number;
    marketingSpend: number;
    deliverySpeed: number;
    discountRate: number;
    expectedRevenue: number;
    expectedTrust: number;
    expectedSellerHealth: number;
    expectedCarbon: number;
    expectedWorkerStress: number;
    expectedHealth: number;
    confidence: number;
    reason: string;
  };
  
  // State Fairness Scores for Map
  stateScores: { [state: string]: { delivery: number; seller: number; satisfaction: number } };
}

// Initial node coordinates for SVG graph
export const DEPENDENCY_NODES: VariableNode[] = [
  {
    id: 'price',
    label: 'Price Level',
    type: 'input',
    description: 'Direct cost of products to consumers. Impacts customer trust and company revenue.',
    influenceScore: 88,
    historicalTrend: [100, 102, 105, 108, 110, 115],
    connectedIds: ['revenue', 'trust', 'seller_health'],
    x: 150,
    y: 120
  },
  {
    id: 'delivery',
    label: 'Delivery Speed',
    type: 'input',
    description: 'Target shipment timeline. Shorter delivery times increase carbon footprint and driver workload.',
    influenceScore: 82,
    historicalTrend: [5, 4, 3, 2, 2, 1.5],
    connectedIds: ['trust', 'carbon', 'worker_stress'],
    x: 150,
    y: 250
  },
  {
    id: 'discount',
    label: 'Discount Rate',
    type: 'input',
    description: 'Promotional discount level. Higher discounts drive sales volumes but squeeze small seller margins.',
    influenceScore: 76,
    historicalTrend: [10, 15, 12, 20, 25, 22],
    connectedIds: ['revenue', 'seller_health', 'waste'],
    x: 150,
    y: 380
  },
  {
    id: 'marketing',
    label: 'Marketing Budget',
    type: 'input',
    description: 'Capital allocated to campaigns. Boosts order volume and brand awareness.',
    influenceScore: 68,
    historicalTrend: [100, 110, 120, 130, 140, 150],
    connectedIds: ['revenue', 'trust', 'waste'],
    x: 150,
    y: 500
  },
  {
    id: 'procurement',
    label: 'Procurement Volume',
    type: 'input',
    description: 'Inventory levels ordered. Over-procurement leads to warehouse waste and write-offs.',
    influenceScore: 62,
    historicalTrend: [5000, 5200, 6000, 7000, 8000, 9500],
    connectedIds: ['waste', 'worker_stress'],
    x: 150,
    y: 620
  },
  
  // Outputs & Social
  {
    id: 'revenue',
    label: 'Revenue Growth',
    type: 'output',
    description: 'Total income generated by platform transactions.',
    influenceScore: 95,
    historicalTrend: [82, 85, 89, 93, 97, 100],
    connectedIds: ['marketplace_health'],
    x: 500,
    y: 120
  },
  {
    id: 'trust',
    label: 'Customer Trust',
    type: 'social',
    description: 'Aggregated consumer trust index based on ratings, returns, and delivery reliability.',
    influenceScore: 90,
    historicalTrend: [88, 87, 85, 84, 82, 80],
    connectedIds: ['marketplace_health'],
    x: 500,
    y: 220
  },
  {
    id: 'seller_health',
    label: 'Seller Health',
    type: 'social',
    description: 'Average profitability, retention and marketplace fairness rating for third-party sellers.',
    influenceScore: 84,
    historicalTrend: [78, 76, 75, 72, 70, 68],
    connectedIds: ['marketplace_health'],
    x: 500,
    y: 320
  },
  {
    id: 'carbon',
    label: 'Carbon Footprint',
    type: 'social',
    description: 'Estimated carbon emissions (CO₂) generated through packaging, logistics, and returns.',
    influenceScore: 78,
    historicalTrend: [100, 105, 112, 118, 124, 132],
    connectedIds: ['marketplace_health'],
    x: 500,
    y: 420
  },
  {
    id: 'worker_stress',
    label: 'Logistics Workload',
    type: 'social',
    description: 'Utilization rates and safety stresses reported by fulfillment and delivery agents.',
    influenceScore: 80,
    historicalTrend: [55, 60, 65, 72, 78, 85],
    connectedIds: ['marketplace_health'],
    x: 500,
    y: 520
  },
  {
    id: 'waste',
    label: 'Inventory Waste',
    type: 'social',
    description: 'Spoiled or discarded stock cost, and warehouse capacity consumption.',
    influenceScore: 70,
    historicalTrend: [8, 10, 12, 15, 18, 22],
    connectedIds: ['marketplace_health'],
    x: 500,
    y: 620
  },
  {
    id: 'marketplace_health',
    label: 'Marketplace Health',
    type: 'output',
    description: 'Weighted score of overall ecosystem health balancing commercial success and societal impact.',
    influenceScore: 100,
    historicalTrend: [92, 90, 88, 86, 85, 83],
    connectedIds: [],
    x: 820,
    y: 370
  }
];

export const STATES_LIST = [
  { id: 'IN-MH', name: 'Maharashtra', lat: 19.75, lng: 75.71 },
  { id: 'IN-KA', name: 'Karnataka', lat: 15.31, lng: 75.71 },
  { id: 'IN-TN', name: 'Tamil Nadu', lat: 11.12, lng: 78.65 },
  { id: 'IN-UP', name: 'Uttar Pradesh', lat: 26.84, lng: 80.94 },
  { id: 'IN-DL', name: 'Delhi', lat: 28.61, lng: 77.20 },
  { id: 'IN-GJ', name: 'Gujarat', lat: 22.25, lng: 71.19 },
  { id: 'IN-WB', name: 'West Bengal', lat: 22.98, lng: 87.85 },
  { id: 'IN-AP', name: 'Andhra Pradesh', lat: 15.91, lng: 79.74 },
  { id: 'IN-KL', name: 'Kerala', lat: 10.85, lng: 76.27 },
  { id: 'IN-RJ', name: 'Rajasthan', lat: 27.02, lng: 74.21 },
  { id: 'IN-MP', name: 'Madhya Pradesh', lat: 22.97, lng: 78.65 },
  { id: 'IN-HR', name: 'Haryana', lat: 29.05, lng: 76.08 },
  { id: 'IN-PB', name: 'Punjab', lat: 31.14, lng: 75.34 },
  { id: 'IN-OR', name: 'Odisha', lat: 20.95, lng: 83.37 },
  { id: 'IN-BR', name: 'Bihar', lat: 25.09, lng: 85.31 }
];

export function runSimulation(inputs: SimulationInputs): SimulationResult {
  const { priceChange, deliverySpeed, discountRate, marketingSpend, procurementVol, crisis } = inputs;
  
  // Base calculations
  let revenueChange = (priceChange * 0.6) + (marketingSpend * 0.25) - (discountRate * 0.15);
  let customerTrust = 85 - (priceChange * 0.45) + (discountRate * 0.2) + (deliverySpeed === 1 ? 5 : deliverySpeed === 2 ? 2 : -3);
  let sellerHealth = 78 - (discountRate * 0.6) - (priceChange * 0.1) + (marketingSpend * 0.1);
  let carbonEmissionChange = 5.0 + (marketingSpend * 0.1) + (procurementVol * 0.1);
  let workerStress = 50 + (marketingSpend * 0.2) + (procurementVol * 0.15);
  let inventoryWasteUnits = Math.max(0, Math.floor(5000 + (procurementVol * 150) - (marketingSpend * 60) - (priceChange * 50)));
  
  // Adjustment based on delivery speed
  if (deliverySpeed === 1) { // Same day
    carbonEmissionChange += 18.5;
    workerStress += 24;
    customerTrust += 4;
  } else if (deliverySpeed === 2) { // 2 day
    carbonEmissionChange += 7.2;
    workerStress += 9;
    customerTrust += 2;
  } else { // 5 day
    carbonEmissionChange -= 4.5;
    workerStress -= 8;
  }

  // Handle Crisis parameters
  let crisisFactorText = '';
  if (crisis === 'flood') {
    revenueChange -= 12;
    workerStress += 25;
    customerTrust -= 15;
    sellerHealth -= 8;
    crisisFactorText = 'Fulfillment centers disrupted due to extreme rain.';
  } else if (crisis === 'fuel_spike') {
    carbonEmissionChange += 3;
    sellerHealth -= 14; // Higher logistics shipping fees
    revenueChange -= 4;
    crisisFactorText = 'High diesel prices squeeze logistics operator margins.';
  } else if (crisis === 'seller_strike') {
    sellerHealth -= 25;
    revenueChange -= 18;
    customerTrust -= 10;
    crisisFactorText = 'Fulfillment stalled due to seller profit squeeze disputes.';
  } else if (crisis === 'festival') {
    revenueChange += 22;
    workerStress += 28;
    inventoryWasteUnits = Math.max(0, inventoryWasteUnits - 1500); // Higher clearance
    customerTrust += 5;
    crisisFactorText = 'Surge in seasonal festival shopping spikes load.';
  }

  // Boundary capping
  customerTrust = Math.min(100, Math.max(0, Math.round(customerTrust)));
  sellerHealth = Math.min(100, Math.max(0, Math.round(sellerHealth)));
  workerStress = Math.min(100, Math.max(0, Math.round(workerStress)));
  carbonEmissionChange = parseFloat(carbonEmissionChange.toFixed(1));
  revenueChange = parseFloat(revenueChange.toFixed(1));
  
  // Waste metrics
  const inventoryWasteCost = Math.round(inventoryWasteUnits * 16.5);
  const wasteRecommendation = inventoryWasteUnits > 8000 
    ? `Reduce procurement volume by ${Math.round((inventoryWasteUnits - 6000) / 450) + 5}% to prevent stock spoiling.`
    : 'Procurement aligns well with demand forecasts.';

  // Trust projected
  const trustProjected90Days = Math.max(0, Math.round(customerTrust - (priceChange > 15 ? 12 : priceChange > 5 ? 5 : 0) - (deliverySpeed === 5 ? 6 : 0)));

  // Detailed scores
  const avgSellerProfit = Math.max(0, Math.round(2400 - (discountRate * 38) + (priceChange * 8)));
  const smallSellerSurvival = Math.min(100, Math.max(0, Math.round(85 - (discountRate * 0.9) - (priceChange * 0.1))));
  const sellerChurnProb = Math.min(100, Math.max(0, Math.round(5 + (discountRate > 20 ? (discountRate - 20) * 1.8 : 0) + (sellerHealth < 60 ? (60 - sellerHealth) * 0.9 : 0))));
  const fairnessIndex = Math.min(100, Math.max(0, Math.round(80 - (discountRate * 0.4) - (priceChange > 10 ? 8 : 0))));
  
  const greenDeliveryPct = Math.round(Math.max(10, Math.min(95, 60 - (deliverySpeed === 1 ? 30 : deliverySpeed === 2 ? 10 : 0))));
  const sustainableShippingScore = Math.round(Math.max(10, Math.min(100, 85 - (carbonEmissionChange > 10 ? carbonEmissionChange * 2 : 0))));

  const warehouseLoad = Math.min(100, Math.max(0, Math.round(45 + (procurementVol * 0.8) + (deliverySpeed === 1 ? 25 : 0))));
  const driverWorkload = Math.min(100, Math.max(0, Math.round(50 + (deliverySpeed === 1 ? 32 : deliverySpeed === 2 ? 12 : -10) + (marketingSpend * 0.1))));
  const deliveryUtil = Math.round(Math.min(100, Math.max(20, 65 + (marketingSpend * 0.4) - (deliverySpeed === 5 ? 12 : 0))));

  // Ethical Risk evaluation
  let ethicalRisk: 'Low' | 'Medium' | 'High' = 'Low';
  let pricingRiskReason = 'Fair & Ethical pricing patterns detected.';
  
  if (priceChange > 12 && discountRate > 15) {
    ethicalRisk = 'High';
    pricingRiskReason = '🚨 Ethical Pricing Risk: Price inflated shortly before announcing discounts.';
  } else if (priceChange > 18 || smallSellerSurvival < 60 || workerStress > 82) {
    ethicalRisk = 'High';
    pricingRiskReason = '🚨 High Risk: Seller welfare compromised or worker stress threshold breached.';
  } else if (priceChange > 8 || discountRate > 25 || workerStress > 70) {
    ethicalRisk = 'Medium';
    pricingRiskReason = '⚠️ Caution: Elevated worker stress and marginal pressure on small sellers.';
  }

  // Marketplace Health calculation (weighted)
  const weightedHealth = (
    (100 + revenueChange) * 0.25 + 
    customerTrust * 0.2 + 
    sellerHealth * 0.2 + 
    (100 - Math.max(0, carbonEmissionChange)) * 0.15 + 
    (100 - workerStress) * 0.1 +
    (100 - (inventoryWasteUnits / 300)) * 0.1
  );
  const marketplaceHealth = Math.round(Math.min(100, Math.max(10, weightedHealth)));

  // Timeline propagation events
  const timeline = [
    { week: 1, title: 'Revenue Signals', description: `Revenue is projected to track at ${revenueChange >= 0 ? '+' : ''}${revenueChange}% under adjustments.`, impact: revenueChange >= 0 ? 'good' as const : 'bad' as const, metric: 'Finances' },
    { week: 4, title: 'Logistics Activation', description: deliverySpeed === 1 ? 'Same-day shipping model increases logistics warehouse pressure.' : 'Fulfillment tracks within expected bounds.', impact: deliverySpeed === 1 ? 'bad' as const : 'neutral' as const, metric: 'Workforce' },
    { week: 8, title: 'Seller Retention Impact', description: sellerHealth < 65 ? 'Small sellers report drop in net margin; seller churn triggers.' : 'Seller community indicates stable metrics.', impact: sellerHealth < 65 ? 'bad' as const : 'good' as const, metric: 'Sellers' },
    { week: 12, title: 'Carbon Peak', description: carbonEmissionChange > 12 ? 'Fuel burn spikes from split-deliveries. CO2 thresholds exceeded.' : 'Logistics footprint holds stable.', impact: carbonEmissionChange > 12 ? 'bad' as const : 'neutral' as const, metric: 'Ecology' },
    { week: 18, title: 'Marketplace Equilibrium', description: marketplaceHealth < 75 ? 'Overall ecosystem health settles lower. Churn begins to impact customer repeat rate.' : 'Ecosystem settles into a positive sustainable loop.', impact: marketplaceHealth < 75 ? 'bad' as const : 'good' as const, metric: 'Ecosystem' }
  ];

  // AI Safer Recommendation
  const recPrice = Math.max(-5, Math.round(priceChange * 0.5));
  const recMarketing = Math.min(45, Math.max(5, Math.round(marketingSpend * 0.8 + 5)));
  const recDelivery = deliverySpeed === 1 ? 2 : deliverySpeed; // shift from Same Day to 2-day
  const recDiscount = Math.round(discountRate * 0.6);
  
  const recRevenue = parseFloat(((recPrice * 0.6) + (recMarketing * 0.25) - (recDiscount * 0.15)).toFixed(1));
  const recTrust = Math.round(85 - (recPrice * 0.45) + (recDiscount * 0.2) + (recDelivery === 2 ? 2 : -3));
  const recSeller = Math.round(78 - (recDiscount * 0.6) - (recPrice * 0.1));
  const recCarbon = parseFloat((5.0 + (recMarketing * 0.1) + (recDelivery === 2 ? 7.2 : -4.5)).toFixed(1));
  const recWorker = Math.round(50 + (recMarketing * 0.2) + (recDelivery === 2 ? 9 : -8));
  const recHealth = Math.round((100 + recRevenue) * 0.25 + recTrust * 0.2 + recSeller * 0.2 + (100 - recCarbon) * 0.15 + (100 - recWorker) * 0.2);

  const aiSuggestion = {
    priceChange: recPrice,
    marketingSpend: recMarketing,
    deliverySpeed: recDelivery,
    discountRate: recDiscount,
    expectedRevenue: recRevenue,
    expectedTrust: recTrust,
    expectedSellerHealth: recSeller,
    expectedCarbon: recCarbon,
    expectedWorkerStress: recWorker,
    expectedHealth: Math.min(100, recHealth),
    confidence: 94,
    reason: deliverySpeed === 1 
      ? 'Shifting from same-day to 2-day delivery significantly reduces driver stress (-15%) and carbon footprint (-11.3%) while maintaining 90% of revenue potential.'
      : 'Moderating pricing hikes and discounts protects small sellers from churn risk while preserving long-term brand equity.'
  };

  // State Fairness heatmap calculator (adds state variance)
  const stateScores: { [state: string]: { delivery: number; seller: number; satisfaction: number } } = {};
  STATES_LIST.forEach((s, idx) => {
    // Metro states (MH, DL, KA, TN) benefit from high delivery, rural suffers
    const isMetro = ['IN-MH', 'IN-DL', 'IN-KA', 'IN-TN'].includes(s.id);
    let deliveryScore = isMetro 
      ? (deliverySpeed === 1 ? 95 : deliverySpeed === 2 ? 88 : 72)
      : (deliverySpeed === 1 ? 42 : deliverySpeed === 2 ? 65 : 78); // same-day delivery has low rural availability!
    
    // Add minor state-specific noise
    const noise = (idx % 5) - 2;
    deliveryScore = Math.max(20, Math.min(100, deliveryScore + noise));

    let sellerScore = Math.round(sellerHealth + (isMetro ? -3 : 4) + (idx % 4));
    let satisfactionScore = Math.round(customerTrust + (isMetro ? 2 : -4) + (idx % 3));

    stateScores[s.id] = {
      delivery: Math.max(10, Math.min(100, deliveryScore)),
      seller: Math.max(10, Math.min(100, sellerScore)),
      satisfaction: Math.max(10, Math.min(100, satisfactionScore))
    };
  });

  return {
    revenueChange,
    customerTrust,
    sellerHealth,
    carbonEmissionChange,
    workerStress,
    marketplaceHealth,
    ethicalRisk,
    inventoryWasteUnits,
    inventoryWasteCost,
    trustProjected90Days,
    avgSellerProfit,
    smallSellerSurvival,
    sellerChurnProb,
    fairnessIndex,
    greenDeliveryPct,
    sustainableShippingScore,
    warehouseLoad,
    driverWorkload,
    deliveryUtil,
    pricingRiskReason,
    wasteRecommendation,
    timeline,
    aiSuggestion,
    stateScores
  };
}

export const CRISIS_DISRUPTIONS = [
  { id: 'none', label: 'Stable Operations', desc: 'No active environmental or socio-economic triggers.' },
  { id: 'flood', label: 'Monsoon Flooding', desc: 'Severely cuts logistics speeds, spikes warehouse load.' },
  { id: 'fuel_spike', label: 'Fuel Price Spike', desc: 'Increases shipping cost; impacts seller payout margins.' },
  { id: 'seller_strike', label: 'Seller Churn Protest', desc: 'Third-party sellers freeze listings over commission levels.' },
  { id: 'festival', label: 'Festival Demand Surge', desc: 'Massive order spike. Tests maximum worker and server capacity.' }
];
